version: '3.5'

services:
  database:
    container_name: database
    image: database
    build: .docker/
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
