apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}
  labels:
    app: {{.Chart.Name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Chart.Name}}
  template:
    metadata:
      labels:
        app: {{.Chart.Name}}
    spec:
      containers:
        - name: petclinic
          image: {{.Values.image.repository}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
          - containerPort: {{.Values.deployment.port}}
          volumeMounts:
          - name: properties
            mountPath: /app/application.properties
            subPath: application.properties
      volumes:
        - name: properties
          configMap:
            name: {{.Chart.Name}}
